[package]
name = "rca"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

[dependencies]
evercrypt = { git = "https://github.com/franziskuskiefer/evercrypt-rust.git", branch="master" }

[dev-dependencies]
rand = "0.7"
